### ISSUE TITLE
Lint should include unused import detection

### ISSUE THREAD

**Issue by xiang-zhu** [mintel/build-harness#28]
Follow the same logic as https://prettier.io/docs/en/comparison.html lint should cover both formatting and code quality check. Currently black and isort provide the check of code formating, but the code quality check for issues like unused import is missing

**Comment by charlieparkes** [comment]
I agree! Would you please include a list of tools, commands, and config you use to accomplish this? I'll get it integrated and open an MR.

**Comment by xiang-zhu** [comment]
The tool I use for this is flake8 https://github.com/PyCQA/flake8 but need to configure it to ignore check we want black to handle

An example config

```
[flake8]
ignore =
	E203, # https://github.com/psf/black/issues/315
	W503, # https://github.com/psf/black/pull/36
	E501, # Let black handle line length
````
