### ISSUE TITLE
Auto-init build harness without running bh/init

### ISSUE THREAD

**Issue by charlieparkes** [mintel/build-harness#64]

**Comment by jtdoepke** [comment]
Also add a sensible default target if the user just calls `make`, such as `help`.

**Comment by nabadger** [comment]
I'm not sure this is required anymore - upstream at least have re-written a portion of this.

I can certainly get upstream+build-extensions working without having to explicty `make init`.

In addition, default targets can be added to calling code `Makefile` like so:

```
-include $(shell curl -sSL -o .build-harness "https://git.io/build-harness"; echo .build-harness)
.DEFAULT_GOAL := help
```

So I don't think it's something that we would set in build-harness itself, but more whatever is managing the app `Makefile`.
